name: build_ErfanGSIs

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL: https://get.mirror2.arrowos.net/download.php?token=l8IOkNSsCKrXotpjQGdeZ0aqbgRT6n5fV1EHUiB9FmvxuczJD73MPLYW2hwA&version=arrow-12.1&variant=official&device=OP4A89
  ROM_NAME: Generic
  BUILD_TYPE: Aonly  
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@maste
           
       - name: Initialization environment
         run: |
            sudo -E apt-get -qq install git wget
       - name: Install pip
         run: |
            sudo apt-get install python-pip #python2
            sudo apt-get install python3-pip #python3
       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/erfanoabdi/ErfanGSIs.git
         
       - name: Fix exit
         run: |
              sed -i 's/\|\| exit 1//g' $GITHUB_WORKSPACE/ErfanGSIs/url2GSI.sh
              sed -i 's/exit 1//g' $GITHUB_WORKSPACE/ErfanGSIs/url2GSI.sh
       
       - name: Setting up ErfanGSI requirements
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs
              mkdir ./output
              sudo bash ./setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: |
              cd  $GITHUB_WORKSPACE/ErfanGSIs
              sudo bash ./url2GSI.sh -c --$BUILD_TYPE $ROM_URL $ROM_NAME

       - name: Zip GSI  
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs/output
              mkdir final
              zip -r final/GSI.zip ./*
       
       
       - name: upload result
         uses: actions/upload-artifact@v1
         with:
           name: my-artifact
           path: ErfanGSIs/output

         
            
