name: build_ErfanGSIs

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL: https://objects.githubusercontent.com/github-production-release-asset-2e65be/443249600/84b00b9d-9c11-43b1-8c25-077eef27f984?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240821%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240821T090607Z&X-Amz-Expires=300&X-Amz-Signature=d7ff7815956e6dc47496531e795aef6f9626b058e6788115825d524f2ae92bcd&X-Amz-SignedHeaders=host&actor_id=89840306&key_id=0&repo_id=443249600&response-content-disposition=attachment%3B%20filename%3DPixelOS_cheetah-13.0-20231003-0850.zip&response-content-type=application%2Foctet-stream
  ROM_NAME: PixelOS_cheetah-13.0-20231003-0850.zip
  BUILD_TYPE: AB 
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: Initialization environment
         run: |
            sudo -E apt-get -qq install git wget
       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/Xionger666/ErfanGSIs.git
              
       - name: Install pip
         run: |
            sudo apt-get install python-pip #python2
            sudo apt-get install python3-pip #python3
         
       - name: Fix exit
         run: |
              sed -i 's/\|\| exit 1//g' $GITHUB_WORKSPACE/ErfanGSIs/url2GSI.sh
              sed -i 's/exit 1//g' $GITHUB_WORKSPACE/ErfanGSIs/url2GSI.sh

       
       - name: Setting up ErfanGSI requirements
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs
              mkdir ./output
              sudo bash ./setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: |
              cd  $GITHUB_WORKSPACE/ErfanGSIs
              sudo bash ./url2GSI.sh -c --$BUILD_TYPE $ROM_URL $ROM_NAME

       - name: Zip GSI  
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs/output
              mkdir final
              zip -r final/GSI.zip ./*
       
       
       - name: upload result
         uses: actions/upload-artifact@v1
         with:
           name: my-artifact
           path: ErfanGSIs/output

         
            
